

CREATE TABLE PERSONA(
IDPERSONA INT IDENTITY(1,1) NOT NULL,
NOMBRE NVARCHAR (25) NOT NULL,
APELLIDO NVARCHAR (50) NOT NULL,
TELEFONO NVARCHAR (50) NULL,
CI NVARCHAR (10) NULL,
CORREO NVARCHAR (20) NULL,
ESTADO NVARCHAR (20) NOT NULL,
PRIMARY KEY (IDPERSONA),
);

CREATE TABLE USUARIO(
IDUSUARIO INT IDENTITY(1,1) NOT NULL,
IDPERSONA INT NOT NULL,
NOMBREUSER NVARCHAR (25) NULL,
CONTRASEÑA NVARCHAR (25) NULL,
FECHA_REGISTRO DATETIME ,
PRIMARY KEY (IDUSUARIO),
FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (IDPERSONA),
);

CREATE TABLE ROL(
IDROL INT IDENTITY(1,1) NOT NULL,
NOMBRE NVARCHAR (25) NOT NULL,
ESTADO NVARCHAR (20) NOT NULL,
PRIMARY KEY (IDROL),
);


CREATE TABLE USUARIOROL(
IDUSUARIOROL INT IDENTITY(1,1) NOT NULL,
IDUSUARIO INT NOT NULL,
IDROL INT NOT NULL,
FECHA_ASIGNACION DATETIME,
ESTADO NVARCHAR (20) NOT NULL,
PRIMARY KEY (IDUSUARIOROL),
FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO),
FOREIGN KEY (IDROL) REFERENCES ROL (IDROL),
);


CREATE TABLE CLIENTEL(
IDCLIENTE INT IDENTITY(1,1) NOT NULL,
IDPERSONA INT NOT NULL,
TIPOCLIENTE NVARCHAR (50) NULL,
CODIGOCLIENTE NVARCHAR(50)NULL,
ESTADO NVARCHAR (20) NOT NULL,
PRIMARY KEY (IDCLIENTE),
FOREIGN KEY (IDPERSONA) REFERENCES PERSONA (IDPERSONA),
);

CREATE TABLE VENTAS(
IDVENTAS INT IDENTITY(1,1) NOT NULL,
IDCLIENTE INT NOT NULL,
FECHA DATETIME,
TOTAL NVARCHAR (50) NOT NULL,
ESTADO NVARCHAR (20) NOT NULL,
PRIMARY KEY (IDVENTAS),
FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE),
);